# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI and Test

on:
  push:
    branches:
      - '*'
      # - '!main' # If we added this we would get all branches _except_ main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    # registry and Scope needed for Publish later
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
        scope: '@infinityworks'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: npm make package-lock if missing
      working-directory: ./api
      run: npm i --package-lock-only

    - name: npm make package-lock if missing
      working-directory: ./client
      run: npm i --package-lock-only

    - name: npm ci
      working-directory: ./api
      run: npm ci

    - name: npm ci
      working-directory: ./client
      run: npm ci

    - name: npm build
      working-directory: ./api
      run: npm run build --if-present

    - name: npm build
      working-directory: ./client
      run: npm run build --if-present

    - name: npm test
      working-directory: ./api
      run: npm test

    - name: npm test
      working-directory: ./client
      run: npm test
